server:
  port: 8000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/users/**
            - id: board-service-jwt
              uri: http://localhost:8081
              predicates:
                - Path=/api/boards
                - Method=POST
              filters:
                - JwtAuthenticationFilter
            - id: board-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/boards/**
#            - id: point-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/point/**

jwt:
  secret: twocowsong-2912ub802nfk39203l102
